package com.laan.sportsda.enums;

public enum PermissionDescription {

    GET_FACULTY, ADD_FACULTY, UPDATE_FACULTY, DELETE_FACULTY,
    GET_DEPARTMENT, GET_DEPARTMENTS, ADD_DEPARTMENT, UPDATE_DEPARTMENT, DELETE_DEPARTMENT,
    GET_PERMISSION, GET_PERMISSIONS,
    GET_ROLE, GET_ROLES, ADD_ROLE, UPDATE_ROLE, DELETE_ROLE,
    GET_MEMBER, GET_MEMBERS, GET_MEMBER_CURRENT
}
